### ISSUE TITLE
Please compile plugin or make jenkins server

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#10]
mvn not work with jdk 8, jre 8, jre 10...
Eclipse compile is very difficult. :(

**Comment by andris155** [comment]
https://jitpack.io/com/github/utarwyn/EnderContainers/v2.1.0/build.log

**Comment by utarwyn** [comment]
Github has just added a new feature which allows me to deploy a Maven package directly on the platform. :heart: So now I will using it to publish new packages of the plugin. (Jitpack is not needed anymore)

You can find them here: [https://github.com/utarwyn/EnderContainers/packages](https://github.com/utarwyn/EnderContainers/packages)
And you just have to follow this tutorial to get access to Github packages on your computer: [https://help.github.com/en/articles/configuring-apache-maven-for-use-with-github-package-registry](https://help.github.com/en/articles/configuring-apache-maven-for-use-with-github-package-registry)

I will install a Jenkins instance soon to automatically compile and deploy my plugin on Github.

**Comment by utarwyn** [comment]
I have installed a Jenkins instance on my personal machine, so now you can easily **download latest development builds** here: https://ci.utarwyn.fr/job/EnderContainers/. You can also **use my plugin with Maven** thanks to my personal Maven repository https://repo.utarwyn.fr.
