### ISSUE TITLE
Remove unused chat prefix and make messages more consistent

### ISSUE THREAD

**Issue by utarwyn** [utarwyn/EnderContainers#127]
**Is your feature request related to a problem? Please describe.**
When creating first version of the plugin I had added a prefix like `[EnderContainers]` in all chat messages. Some server owners told me that they would like to change it. As I think it is not useful at all I would like to remove it completly. **It could be a nice thing to also make all chat messages more consistent.**

**Describe the solution you'd like**
Remove unused chat prefix and make messages more consistent.

**Additional context**
![first screenshot](https://cdn.discordapp.com/attachments/817451750671908904/817457518917058600/unknown.png)

Thanks **LordVZlomka** for the feature idea.

**Comment by roy0510** [comment]
it would be good to delete it, since in the same message you can edit it at ease!

**Comment by utarwyn** [comment]
Yes that is my opinion too! I will work on that for the next release :)

**Comment by TheStilk** [comment]
Чел если нужно могу помочь
