### ISSUE TITLE
backup exception

### ISSUE THREAD

**Issue by Sylensky** [utarwyn/EnderContainers#129]
**Versions**

EnderContainers version:
![image](https://user-images.githubusercontent.com/57076968/111066565-f640e480-84bf-11eb-9a98-141930783523.png)

Platform version:
git-Paper-547 (MC: 1.16.5)

**Describe the bug**

The backup command throws an exception when trying to do /ecp backup create <name>

**To Reproduce**

1. Update endercontainer to latest version
2. try to /ecp backup create <name>
3. 
![image](https://user-images.githubusercontent.com/57076968/111066623-45871500-84c0-11eb-83dc-a56e23dace7d.png) seeing that backup is getting created.
4. watch console for errors like below

**Expected behavior**

Backup gets created successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/57076968/111066665-76ffe080-84c0-11eb-815e-a478873241a0.png)

**Comment by utarwyn** [comment]
Hello! Thank you for this report.

I have replaced the base64 string representation of a chest in the database to a `NULL` value to optimize size of data. But I forgot to update the related backup system. I will work on that!

**Comment by utarwyn** [comment]
This should be fixed! The fix will be included in the next minor release.
You can try it today by downloading the latest jar file from my personal website: https://utarwyn.fr/ecp/master.jar

Can you give me feedback about it @Sylensky? Thank you!

**Comment by Sylensky** [comment]
I did give your latest build a shot and seems like the issue is no more, thanks!
