### ISSUE TITLE
Issue: Bug report

### ISSUE THREAD

**Issue by brmghme** [utarwyn/EnderContainers#157]
I did this but it only works when I type /ec
But when I left click on enderchest it doesn't open

**Comment by CrispyDairy** [comment]
Make sure you're not in a worldguard, I thought this at first too. It doesn't work in worldguard regions

**Comment by utarwyn** [comment]
@brmghme: I don't understand.. Do you have more info about the problem? An error log? A message in your chat when trying to open it using right click?

@CrispyDairy: why does it not work in WorldGuard regions? Do I need to do a bugfix here?

Thank you!

**Comment by CrispyDairy** [comment]
I'm not quite sure, I didn't look into it further because I only have my spawn protected under worldguard. And I don't need enderchests there. I can run some debug for you if you'd like

**Comment by utarwyn** [comment]
> I'm not quite sure, I didn't look into it further because I only have my spawn protected under worldguard. And I don't need enderchests there. I can run some debug for you if you'd like

@CrispyDairy: as explained in the wiki page [WorldGuard integration](https://github.com/utarwyn/EnderContainers/wiki/Integrations#worldguard), it automatically protects enderchests from being used based on your zones flags. If a zone denies INTERACT or USE flag, it will prevent players to use enderchests. I think there is no problem with that system :+1:

**Comment by CrispyDairy** [comment]
Ah, I guess it also stops region owners from opening them. Not an issue though :)

**Comment by utarwyn** [comment]
@brmghme Any news on your problem with the plugin?
