### ISSUE TITLE
Duplication Issue

### ISSUE THREAD

**Issue by nivcoo** [utarwyn/EnderContainers#158]
Hello, i've duplication issue with the latest version in 1.12.2

Place item in your /ec 2 for example 
Quit the server and join it and run / ec 2, before the GUI opens, execute the same command, after that you can get the item without editing the enderchest, because the previous gui will be replaced by the new openned gui

**Comment by nivcoo** [comment]
You must place big item (With multiple datas)

**Comment by utarwyn** [comment]
Hello! I will try to reproduce the issue, as I want to release a new release with Minecraft 1.17 support, I will try to fix that duplication issue before. I'll keep you informed :+1:

**Comment by nivcoo** [comment]
I made a fix for my server, in fact we can open an enderchest twice if the load is long so the first time we can modify the enderchest and when the second opens on top then the changes are not saved. To solve this I added a list of users which increments when a player executes / ec or clicks on an auction and is deleted when the loading is finished. 
It's not 100% optimized but it works https://pics.revolis.fr/2021-07/31/15-11_P1Mj.png

**Comment by utarwyn** [comment]
ugh.. I do not have thinking about that possible issue..! Thank you for the details it will help me a lot to fix that 🥇

**Comment by nivcoo** [comment]
Yes because at the first /ec the playercontext is loaded and during its loading we can redo a load and therefore have this problem

**Comment by nivcoo** [comment]
But it only works when the data to load is big and only with the YML and not the mysql

**Comment by nivcoo** [comment]
Also, can you add an otpion to configure the prefix of command ? Because i have to use my fork to edit the prefix

**Comment by utarwyn** [comment]
In next major version of the plugin **(v2.3.x)**, the chat prefix has been removed :+1:
Check that issue in which we have discussed about it: #127

**Comment by nivcoo** [comment]
Okay thx,when the update will be released ?

**Comment by utarwyn** [comment]
That's a big question.. I am not as active as I would like to be on the development of this plugin... so unfortunately I cannot say a date for now. I will already release an update with all duplication bugfixes and Minecraft 1.17 support.

**Comment by utarwyn** [comment]
That duplication problem has already been reported on holograms (in the issue #125). I have done the fix on them but not on the enderchest manager class. Both systems should be ok now. I have done some tests with a very long loading task and it works well.

**Comment by nivcoo** [comment]
Have you reproduce the issue before the fix to compare the situation ?

**Comment by utarwyn** [comment]
Yes I have reproduced the exact issue you described in your first post 👍 And after the bugfix that works fine!

**Comment by nivcoo** [comment]
Okay thx :p is it fixed also when we click on enderchest ?

**Comment by utarwyn** [comment]
Yes! Loading state of a player context is now handled at the code base. So it benefits holograms, opening of enderchests with the command or by clicking on it. I intentionally increased duration of loading task to test this and it's ok

**Comment by nivcoo** [comment]
Okay thx

**Comment by nivcoo** [comment]
I saw your changes and you do the same thing of me, so now i will wait the update :p
