### ISSUE TITLE
Not valid parameters message no translatable

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#16]
![50373218-aa05e300-05db-11e9-8f3a-a03f7cb6ab2d](https://user-images.githubusercontent.com/8324198/50382549-bacd5c00-06a2-11e9-8729-5985396203ec.png)

**Comment by utarwyn** [comment]
I will work on that, thank you!

**Comment by utarwyn** [comment]
This feature has been added with this commit: d7f89e4d1c7ad0e4d60764126afe8adaef8449a1
I hope that it was what you wanted. 👍
