### ISSUE TITLE
Except first one other slots can not be used it closes ec

### ISSUE THREAD

**Issue by superkarli9** [utarwyn/EnderContainers#17]
hey like is i said one of my player said that he cant use other slots when he tries to put it closes the ender chest and i tried to do my self but his ender chest was really buggy i tried to remove his data but it didnt work out too

**Comment by utarwyn** [comment]
Hello @superkarli9 
Thank you for your feedback about the plugin!

I need more information to fix the problem that you have.
**What's your server version/type? Have you an error in the console?**

To remove all the data of a player, you have to go inside the `enderchests/` folder and remove the file with the UUID of the player. At this time there is no command to do it automatically... I add this feature to my todo-list.

Best regards

**Comment by superkarli9** [comment]
Server version : 1.11.2
Error : Yea it gives an error log saying "there's an exception with endercontainers..."

**Comment by utarwyn** [comment]
Ok... So I have to make errors clearer because this one cannot help me to fix the bug. :cry: 
This is maybe due to wrong item data stored inside one of its enderchest. Do you have the bug after removing all its data?

Thank you

**Comment by utarwyn** [comment]
As this issue is old and does not have any answer, I consider that it is outdated.
If you still have the same problem, don't hesitate to open a new issue with more information.
