### ISSUE TITLE
Player's can't open there ender containers

### ISSUE THREAD

**Issue by LuisRavenFlame** [utarwyn/EnderContainers#176]
**Versions**

EnderContainers version:
Platform version: Spigot

**Describe the bug**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by utarwyn** [comment]
Hello, thank you for the feedback. Can you give me more information about the problem?
Console errors? Are player OP? Which permissions do you give to them?

**Comment by utarwyn** [comment]
Closed for inactivity. Reopen it if you still have the problem, but with more infos please 👍
