### ISSUE TITLE
Locales File into jar

### ISSUE THREAD

**Issue by nivcoo** [utarwyn/EnderContainers#188]
Hello, i've build the next branch but without editing the in jar message file we can't edit message. (The plugin only get injar file and not in folder of plugin)

**Comment by utarwyn** [comment]
Hello @nivcoo, using latest development build you can set configuration key **"locale"** to value `custom` and then edit the file named `locale.yml` in the plugin folder (you need to start your server before, so the plugin can create the file).

**Comment by nivcoo** [comment]
Where is the dev build ? Because ive manually built the plugin

**Comment by nivcoo** [comment]
Okay i found it https://ci.utarwyn.fr/job/EnderContainers/ thx :p

**Comment by nivcoo** [comment]
It works thx
