### ISSUE TITLE
Prefix Problem

### ISSUE THREAD

**Issue by TeQTabanca** [utarwyn/EnderContainers#191]
**Is your feature request related to a problem?**
**Yes, language problem.**

**Describe the solution you'd like**
**It would be great if we could write custom prefixes.**

**Additional context**
![Endercontainers Prefix](https://user-images.githubusercontent.com/89253304/149165905-ef704f09-8f19-43f7-94be-be8e04517263.png)

**Comment by utarwyn** [comment]
Hello @TeQTabanca, your idea goes in the same way as the issue #127.
I found out from the server owners that this prefix was not really useful anymore... so I removed it from **v2.3.0** (next release)

**Comment by TeQTabanca** [comment]
**When is v2.3.0 expected to arrive?**

**Comment by utarwyn** [comment]
ugh.. that's a good question. I'm not as active as I would on the plugin so I'm way behind schedule. Sorry for that.
There are still a lot of features to add for 2.3.0: https://github.com/utarwyn/EnderContainers/milestone/2

You can download a **development build** of that v2.3.0 from my [personal integration service](https://ci.utarwyn.fr/job/EnderContainers/).
Keep in mind that these builds can be unstable and not recommended if you already have data using v2.2.x.

**Comment by TeQTabanca** [comment]
**I wish you had removed the direct prefix.**

![X prefix](https://user-images.githubusercontent.com/89253304/149184770-a446c796-2446-4ace-849a-7b7ad497651e.png)

### In addition, there is no locale.yml in the EnderContainers file in 2.3.0!

![endercontainers file](https://user-images.githubusercontent.com/89253304/149185497-5b68d1ce-7b18-45bb-b994-c18a7d492b91.png)

**Comment by utarwyn** [comment]
You mean.. also removing the symbol? Why?
You have to set configuration key `locale` to **"custom"** in order to have a custom `locale.yml` file created in the plugin folder.

**Comment by TeQTabanca** [comment]
> You mean.. also removing the symbol? Why? You have to set configuration key `locale` to **"custom"** in order to have a custom `locale.yml` file created in the plugin folder.

**Because in the plugin messages I use, it says [Plugin Name System]. The symbol there corrupts the message.**

### I set the config key locale to custom but unfortunately nothing changed.

**Comment by TeQTabanca** [comment]
> Hello @nivcoo, using latest development build you can set configuration key **"locale"** to value `custom` and then edit the file named `locale.yml` in the plugin folder `(you need to start your server before, so the plugin can create the file)`.

### I restarted the server still didn't work.

**Comment by TeQTabanca** [comment]
**Anyway, when the 2.3.0 spigot comes, I'll download it.**

### Thank you for your time. I hope you make version 2.3.0 quickly. 😊
