### ISSUE TITLE
Can open enderchest even if PlayerInteractEvent is canceled, any way to solve?

### ISSUE THREAD

**Issue by afoxxvi** [utarwyn/EnderContainers#196]
I have a plugin that may cancel PlayerInteract Event, however enderchest was still opened.
I don't want player can open enderchest even if I canceled the interact event because I have something else to do.

**Comment by utarwyn** [comment]
Hello! As you can see in the code below, I do not check if the event has already been cancelled.
I forgot to handle this case, I'll change that. Thanks for the feedback!

https://github.com/utarwyn/EnderContainers/blob/1539b19a14b7f656480c4ddce933a006a87e7ac7/plugin/src/main/java/fr/utarwyn/endercontainers/enderchest/listener/EnderChestListener.java#L53-L57

**Comment by afoxxvi** [comment]
OK, thanks a lot!
