### ISSUE TITLE
2.0.0 not being able to read already existing MySQL data

### ISSUE THREAD

**Issue by ChunkieMiner** [utarwyn/EnderContainers#2]
https://pastebin.com/sGLSMSG0

Enderchest contents are not accessible, had to revert to the version before 2.0.0 so I can get access to all the enderchest contents again.

**Comment by utarwyn** [comment]
I will look at this issue. Thanks

**Comment by utarwyn** [comment]
Hello, have you done the migration for 2.X versions? Have you got any error?
(Normally it runs automatically when you start the server)

![image](https://user-images.githubusercontent.com/9255967/34569063-e888a4de-f167-11e7-9755-b1e90cc0ac2c.png)

In my case I have no error after it and all enderchests can be opened.
Is anybody else has the bug?

Regards.
