### ISSUE TITLE
1.19.2 Data is not archived

### ISSUE THREAD

**Issue by andy3559167** [utarwyn/EnderContainers#207]
paper 1.19.2-132
2.2.3-dev
When the server is shut down with /stop
Items just put in will not be stored
Causes player items to disappear

**Comment by utarwyn** [comment]
Hello! Sorry for the answer delay.. Did you have the problem after a MC migration?
No console error? Player is still connected during the `/stop`? I cannot reproduce it on my local server..

**Comment by utarwyn** [comment]
Closed for inactivity. Reopen it if you still have the problem, but with more infos please 👍
