### ISSUE TITLE
1.14.1 update?

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#21]
Please update this plugin for 1.14.1.

**Comment by utarwyn** [comment]
Hello @andris155,

I will work to update the plugin to this Minecraft version as soon as possible.
Thank you for the feedback! :+1:

Regards.

**Comment by utarwyn** [comment]
I've made a commit to support **1.14 versions** of **Bukkit/Spigot**.
You can see all modifications in the commit 4ef871742391c329efc2e629e13e4eba22a805df.

I've seen that there is a little freeze when loading a main menu for the first time. I will try to deal with it as soon as I can.

If you see a bug causes by theses changes, don't hesitate to give a feedback about it.

**Comment by andris155** [comment]
Works perfectly. Thanks.
