### ISSUE TITLE
Error to use /ec

### ISSUE THREAD

**Issue by giorgex36** [utarwyn/EnderContainers#214]
version:2.2.2
the wiki is wrong because in the wiki it tells me that there is a specific command for users to open their enderchest but it doesn't work since users don't have the command, what would be the permission for users to open their enderchest, I'm using luckperms

**Comment by utarwyn** [comment]
Hello! So, command is not available for players when you add them permission `endercontainers.cmd.enderchests`?

The wiki page explains that you have to add a prefix before the permission in the table: https://github.com/utarwyn/EnderContainers/wiki/Command-List

**Comment by giorgex36** [comment]
If I already tried all the ways and none allows users to have access to /ec despite having put all the prefixes

**Comment by Wastinqs** [comment]
Same here
