### ISSUE TITLE
DUPE!

### ISSUE THREAD

**Issue by energooooo** [utarwyn/EnderContainers#229]
**Versions**

EnderContainers version: 2.3.0-dev
Platform version: Purpur-1.16.5

**Describe the bug**
My players have found that if they pick up an item from an ender chest on server A and log in to server B, that item will still remain with the fact that it was picked up on another server.

**To Reproduce**
1. Put an item in an ender chest.
2. Rejoin
3. Pick it up
4. Go to another server with the same plugin and a database connected to this one
5. Pick up an item exactly the same as you picked up on another server

**Expected behavior**
The item was supposed to be gone. it was taken from another server.

**Screenshots**
In this video, you can see that the player took the item from the ender chest. Switched to another anarchy and put them in his inventory (He sold them at auction, but that's not important. He could just put them in a chest). He switched to another anarchy and the resources still remained, although he took them on another server.

https://youtu.be/2508dUPn90M

**Comment by EneRGO22** [comment]
I will add that this does not work with all players, and not on all anarchies.
Plugin configuration on all servers is the same.

**Comment by utarwyn** [comment]
Hello! Sorry for the inconvenience, multi-servers feature is not supported in the plugin yet. Issue #172 has been created on the subject to add this support. Sorry I haven’t worked on it yet, it's true that the feature request is pretty old, I am not very active on the development of the plugin..
