### ISSUE TITLE
/ecp open for offline players not working

### ISSUE THREAD

**Issue by ChuteSpyro** [utarwyn/EnderContainers#232]
**Versions**

EnderContainers version:Endercontainers-2.2.2.jar
Platform version:paper-1.19.4-516.jar

**Describe the bug**

If you try to open a player's enderchest while they are offline, nothing happens in game. And a block of error appear on the console.

**To Reproduce**

1. Let a player use their enderchest.
2. Disconnect this player.
3. Execute /ecp open THISPLAYERNAME

**Expected behavior**

I expect it to open this player's enderchest the same as if they were online

**Screenshots**

![Capture d'écran 2023-04-22 075152](https://user-images.githubusercontent.com/97618448/233765479-f1b65aa7-ec52-4caf-b2d1-297658457f46.png)
![Capture d'écran 2023-04-22 075252](https://user-images.githubusercontent.com/97618448/233765492-7a5de079-d492-4a0f-a7e5-f53d775241a8.png)

**Comment by utarwyn** [comment]
Hello! Oops, this system is pretty old and I haven't checked it in the last few months. I'll check it out..
A Mojang API that the plugin uses seems to have been deactivated, I think I have to find a workaround 😄

**Comment by BoomerSchmirtz** [comment]
Hey any update on this bug? :D

**Comment by utarwyn** [comment]
@ChuteSpyro @BoomerSchmirtz I have changed the URL to retrieve player names.

Can you tell me if this works for you with the latest version 2.2.3-dev?
You can download builds here: https://github.com/utarwyn/EnderContainers#downloads

**Comment by utarwyn** [comment]
Hello! In the absence of a reply, I'll assume that the bug has been resolved.
If you still have the problem, please feel free to reopen the ticket or create a new one.
