### ISSUE TITLE
worldguard can't open chest

### ISSUE THREAD

**Issue by STEVE1010101** [utarwyn/EnderContainers#234]
![image](https://user-images.githubusercontent.com/70594985/236694096-e1166f11-4bed-4352-b1fc-44ce5eff5470.png)
both two have set to allow, but still can't open enderchest

**Comment by STEVE1010101** [comment]
nvm i find chest-access
but i think wiki can have some little change

**Comment by utarwyn** [comment]
Hello! Oops sorry this changes has been done in #200 and I forgot to update the wiki page, I'm doing it now.
Thanks for the feedback anyway 😄
