### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by MaxJoker149** [utarwyn/EnderContainers#246]
Hi! I hope you're well.

Sometimes my server goes down and all the players lose items in their ender chests, apparently they are not saved if the server does not close normally, I use mysql with the plugin, you could make the item registration instantly or in timeslots?

**Comment by utarwyn** [comment]
Hello @MaxJoker149! You lose all the changes made by players who are still connected when your server crashes. Is that right?
Indeed, this is a known issue discussed in #231, I need to add a mode for saving chests when saving the world (work started in the PR). The goal would be to offer three save modes: at the same time as the world (this would be the default mode), when logging out or when closing the chest.

What do you think of this idea? Could this solve your problem?

**Comment by MaxJoker149** [comment]
Hi! Without a doubt it is a fantastic solution!

**Comment by utarwyn** [comment]
Resolved by #261. You can re-open the issue or create a new one if the problem persists. Thank you!
