### ISSUE TITLE
Request to add custom name function for the final EnderChest

### ISSUE THREAD

**Issue by Yurium7** [utarwyn/EnderContainers#260]
Add custom text functionality/placeholders for storing content quantity for EnderChest titles and EnderChest container titles

![image](https://github.com/utarwyn/EnderContainers/assets/133829524/f65c5d86-a289-47cf-aba1-20646010690d)
![image](https://github.com/utarwyn/EnderContainers/assets/133829524/621af63f-f195-4f6f-a2b4-2c3490dff8a6)
Add custom text functionality here 
For example, like this ![image](https://github.com/utarwyn/EnderContainers/assets/133829524/50534250-5a02-4f21-8020-fb76dfbef480)

**Comment by utarwyn** [comment]
Hello @Yurium7! Thank you for using the plugin.
Your proposal is very interesting, and seems to have already been raised in ticket #92.

This feature is already available for testing in [version 2.3.0-dev](https://github.com/utarwyn/EnderContainers?tab=readme-ov-file#downloads) of the plugin.
