### ISSUE TITLE
Cannot download beta/dev jar from github (utarwyn.fr)

### ISSUE THREAD

**Issue by hkkongou** [utarwyn/EnderContainers#266]
**Versions**

EnderContainers version:
Platform version:
2.3.0-dev

**Describe the bug**
I am trying to download from these links in github at https://github.com/utarwyn/EnderContainers .
![image](https://github.com/utarwyn/EnderContainers/assets/61608872/32219447-329f-4153-a9fc-1ea25e94d7ff)

show 404 not found or CA error
![image](https://github.com/utarwyn/EnderContainers/assets/61608872/a986e877-c5df-4b5c-aee6-14cc7e9fe0b7)

I tried to build the jar by myself by cloing from github using git, but i cannot build in my windows desktop, so i need to download jars

**To Reproduce**

press the link

**Expected behavior**

can download file

**Screenshots**

provided above

**Additional context**

**Comment by utarwyn** [comment]
Hello! Sorry for the disruption, this should be fixed now!
