### ISSUE TITLE
Bstats need to update

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#31]
https://bstats.org/getting-started/include-metrics

**Comment by utarwyn** [comment]
The official Maven repository of Bstats seems to have changed.
I will change that asap :smile: Thank you for the feedback.

**Comment by utarwyn** [comment]
This should be resolved with the commit b27931f96e4328e6cc86eaf9765c75a5b307db65.

**Comment by andris155** [comment]
Thanks
