### ISSUE TITLE
GitHub Actions - build plugin jar

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#36]
The Slimefun plugin use GitHub Actions to the build plugin jar.
This is totally free.
Please setup Actions for Endercontainers.
https://github.com/TheBusyBiscuit/Slimefun4

**Comment by utarwyn** [comment]
I have not tested it yet, but I will try to setup it for the plugin asap :)

**Comment by microwin7** [comment]
Install Chocolatey. Onward cmd or powershell: choco install maven; mvn package
Preliminary cut from code factions. If there are problems with compilation
