### ISSUE TITLE
onlyShowAccessible: true - Problem

### ISSUE THREAD

**Issue by radek203** [utarwyn/EnderContainers#40]
When I turned on the option in config: onlyShowAccessible: true after the player tries to give the item to an empty place, I don't know it, but this item cannot be recovered, it should be blocked from putting items there.
![2020-02-04_22 09 30](https://user-images.githubusercontent.com/57212337/73787316-57659700-479b-11ea-846a-bcb35b2240bf.png)

EnderContainers-2.2.0-bug-3
Spigot: 1.12.2
[ProtocolLib] Enabling ProtocolLib v4.5.1-SNAPSHOT-b445

**Comment by utarwyn** [comment]
Hello @radek203! Yes, it's a bug 😅 I will fix it as soon as I can.
Thank you for the feedback!

**Comment by utarwyn** [comment]
This bug should be fixed with the referenced commit above.
I've made dragging and clicking forbidden in restricted menus.

Here is a little preview:
![Fix preview](https://i.gyazo.com/d575c246655a0809175a5d2b1e718911.gif)

Best regards.
