### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#41]
<img width="849" alt="Capture" src="https://user-images.githubusercontent.com/8324198/76146320-f4b13500-6091-11ea-8e8b-64d496d60f64.PNG">

**Comment by utarwyn** [comment]
The repository that Maven uses to retrieve artifacts for **Factions v2+** seems to be down... (https://fractal.lindegaard.one:8187, 404 error), I will try to use another one.

**Comment by andris155** [comment]
Faction no longer receives updates. Why don't drop this dependency?

**Comment by utarwyn** [comment]
I was thinking about that idea too. But I don't know if the official plugin is still used a lot (with compatible servers) or if a fork has been made based on the v2.

**Comment by andris155** [comment]
Add dependencies statistic to bstats.

**Comment by utarwyn** [comment]
Until this feature is added, I will try to use another repository for this artifact.

**Comment by andris155** [comment]
Thanks!
