### ISSUE TITLE
Deprecated method 1.12.2

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#5]
![kepkivagas](https://user-images.githubusercontent.com/8324198/42501517-2c4723b2-8434-11e8-9b60-bc9f55f07be5.PNG)

**Comment by utarwyn** [comment]
@andris155: the deprecated method has been removed in the commit 0210d5a08c7b8553732a1d7a9aa2f485accdf3be 👍 
Hope that It will fix the error with your IDE (It works for me with Intellij Idea).
