### ISSUE TITLE
Send dependencies usage to bStats

### ISSUE THREAD

**Issue by utarwyn** [utarwyn/EnderContainers#51]
As mentionned in https://github.com/utarwyn/EnderContainers/issues/41#issuecomment-596237470, it would be a good idea to send dependencies usage to the **bStats service** (https://bstats.org/plugin/bukkit/EnderContainers/1855) to know if one of them is no more used by server owners.

**Comment by andris155** [comment]
Only 43 servers use this cool plugin. :/
If you upload the new jar on the Spigot and on the GitHub release page would maybe grow to 100+ servers.

**Comment by andris155** [comment]
The maven compile method too difficult the general server owners.

**Comment by utarwyn** [comment]
Yep of course! Thank you for your awesome support :heart: I'm excited to upload the new version on Spigot, soon!

**Comment by utarwyn** [comment]
Dependencies usage of the plugin is now available here: https://bstats.org/plugin/bukkit/EnderContainers/1855#dependenciesUsage

These data will be used in the future to remove or add new dependencies based on their usage.
