### ISSUE TITLE
Error load Backup with DB

### ISSUE THREAD

**Issue by microwin7** [utarwyn/EnderContainers#56]
![image](https://user-images.githubusercontent.com/12544425/77374288-59031280-6d7b-11ea-8d6a-42a32bacb0b7.png)
![image](https://user-images.githubusercontent.com/12544425/77374324-6fa96980-6d7b-11ea-8c12-0cb3cae8e2fc.png)
https://imgur.com/a/T8IJVay

**Comment by utarwyn** [comment]
Hello @microwin7, I haven't seen this bug in the past, that's strange. What software and version of database server are you using? I will investigate more to know if there is an incompatibility or something else.

In general I'm not very happy with my backup management system. I should rework on it in the future. Anyway, thank you for the feedback!

**Comment by microwin7** [comment]
MySQL MariaDB

**Comment by utarwyn** [comment]
Hello @microwin7,
I have changed the way to replace enderchests when loading a backup. This should now works for you thanks to the latest commit 772129b0352341244d3582587412265e14e10316. **Give me a feedback on that!**

I have compiled the latest source code with the fix for you: [EnderContainers-2.2.0-772129b.zip](https://github.com/utarwyn/EnderContainers/files/4561747/EnderContainers-2.2.0-772129b.zip)

**Comment by utarwyn** [comment]
@microwin7, have you tested with the fix? Is the problem stills present on your server?

**Comment by microwin7** [comment]
Sorry. I could not check for a long time. Backups work, thanks =)

**Comment by microwin7** [comment]
It’s really strange that sometimes after restarting, I can’t open the chest on the right click, but only with the command

**Comment by microwin7** [comment]
https://pastebin.com/X02Pbm4d
Error((

**Comment by microwin7** [comment]
![image](https://user-images.githubusercontent.com/12544425/83335273-55789400-a2b4-11ea-8b53-4e2433a0566b.png)
spigot 1.8.8
Please check all classes to work with this version, where there is only one hand and there may be some similar problems. Just as I look there is no version manager

**Comment by utarwyn** [comment]
Yes sorry about that! As I have already mentioned it in another issue, there is a problem with the method `getItemInMainHand()`. I will fix it!

**Comment by utarwyn** [comment]
I will also try to create a build pipeline for each versions of Minecraft on GitHub to be sure that all classes are compatible with these versions.

**Comment by microwin7** [comment]
wait, I’ll offer a solution in a couple of minutes

**Comment by microwin7** [comment]
check

**Comment by microwin7** [comment]
I need to add to pom version 1.8, I think

**Comment by utarwyn** [comment]
I will check that! Thank you for the contribution yep :+1:

**Comment by microwin7** [comment]
strange, not working for some reason)
maybe you have a better idea for implementation will be

**Comment by microwin7** [comment]
![image](https://user-images.githubusercontent.com/12544425/83336321-2e719080-a2bb-11ea-8d87-c83d4e0c12f6.png)
for some reason, it’s called in my code anyway, verification further, not 1.8

**Comment by microwin7** [comment]
https://pastebin.com/GCg7gpxD
replaced .getItemInMainHand () with .getItemInHand () and this is what I got

**Comment by microwin7** [comment]
https://pastebin.com/VyhqUjty
I strongly apologize, as it turned out I was not completely convinced of the work, checked on clean (new) databases, and when I put the plug-in on the base now, I got such an error when taking data. Given that I deleted the table for backups in advance, it means an error with existing player inventories

**Comment by microwin7** [comment]
![image](https://user-images.githubusercontent.com/12544425/83340822-61307e80-a2e5-11ea-8d04-2cd0215429cf.png)
Left new
Right old

**Comment by utarwyn** [comment]
Yep I have changed how base64 data strings are stored. I'm now using the "Java traditional way" which is not using break lines in the serialized data. **BUT** this should not causes any problem because the new class supports both formats for deserialization. Can you send me the input data of the `decode` method?

See it in action here:
https://github.com/utarwyn/EnderContainers/blob/9fc4ea27b0fb6bae7ec0fd300037f731ce22c810/plugin/src/main/java/fr/utarwyn/endercontainers/storage/serialization/Base64ItemSerializer.java#L27-L72

**Comment by microwin7** [comment]
![image](https://user-images.githubusercontent.com/12544425/83341599-b53f6100-a2ed-11ea-8439-90cc582bacff.png)

**Comment by microwin7** [comment]
In the version from March, this was not

**Comment by utarwyn** [comment]
> https://pastebin.com/GCg7gpxD
> replaced .getItemInMainHand () with .getItemInHand () and this is what I got
> Error due to PlotSquared

Which version of PlotSquared do you use? The plugin only supports **v5+** now.

**Comment by utarwyn** [comment]
I have also replaced the method `getItemInMainHand()` with `getItemInHand()` to solve your issue with 1.8 version of MC in the commit f0b3e3a28655bdb874c91323a7528165e1afefce.

**Comment by utarwyn** [comment]
@microwin7 Are all your problems been solved? If you want me to add support for another version of **PlotSquared**, please create a new issue. Also I have done some tests with the latest development version and the data loading (items) seems to work fine.

**Comment by utarwyn** [comment]
I have fixed the bug when **loading data of enderchests saved with version 2.1.0 of the plugin**. Sorry I thought this bug had been fixed earlier! You can download the Jar with the fix here: https://ci.utarwyn.fr/job/EnderContainers
