### ISSUE TITLE
Build failure plotsquared

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#59]
<img width="856" alt="Capture" src="https://user-images.githubusercontent.com/8324198/79690750-58677a00-825c-11ea-8f53-dc49df2729a6.PNG">

**Comment by utarwyn** [comment]
omg I'm fed up of these problems with dependencies :joy: I will check, sorry

**Comment by utarwyn** [comment]
The PlotSquared project has been removed from their Jenkins instance and Maven repository, I don't know why :thinking: Maybe we should just **wait for a fix or an alternative**... That's such a pain... I think that I will **put all dependencies on my own Maven repository** to avoid these problems.

The Jenkins instance: https://ci.athion.net/

**Comment by andris155** [comment]
https://www.spigotmc.org/resources/plotsquared-v5.77506/

**Comment by andris155** [comment]
"PlotSquared v4 won't receive updates anymore. We suggest updating to v5."

**Comment by andris155** [comment]
Thanks!

**Comment by utarwyn** [comment]
@andris155 No problem! Thank you for the feedback :)
