### ISSUE TITLE
Enderchest locked - Information settings

### ISSUE THREAD

**Issue by radek203** [utarwyn/EnderContainers#65]
I suggest that you add what you want to show when the enderchest is blocked
If it is blocked, e.g. it would be possible to hide 0/27 and "enderchest empty" in config or set what you want to show there
![2020-05-25_22 25 54](https://user-images.githubusercontent.com/57212337/82841592-f17e5600-9ed6-11ea-92ff-f18383305579.png)

**Comment by utarwyn** [comment]
Nice feature! Thank you for the idea :+1:
