### ISSUE TITLE
Adding option between Full and Empty

### ISSUE THREAD

**Issue by radek203** [utarwyn/EnderContainers#66]
I suggest adding an option, message should be displayed when the enderchest is not full or not full.
![2020-05-25_22 31 32](https://user-images.githubusercontent.com/57212337/82841877-e4159b80-9ed7-11ea-9048-4640aa452eb2.png)
![2020-05-25_22 31 21](https://user-images.githubusercontent.com/57212337/82841883-e841b900-9ed7-11ea-98ad-e6543c1e8a33.png)
![2020-05-25_22 31 45](https://user-images.githubusercontent.com/57212337/82841886-eaa41300-9ed7-11ea-9d91-7172801fee3e.png)

**Comment by utarwyn** [comment]
Nice idea! I will look into that to add it to the plugin.
