### ISSUE TITLE
Mini Bug -  Quick clicks on a locked slot

### ISSUE THREAD

**Issue by radek203** [utarwyn/EnderContainers#67]
As in the subject, the sound of spam clicking on a locked slot is unbearable! :)
At least on this version what I am: 1.8.8

EnderChestHubMenu
MiscUtil.playSound(player, "ANVIL_BREAK", "BLOCK_ANVIL_BREAK");

I had to exchange it for
MiscUtil.playSound(player, "GLASS", "GLASS");

**Comment by radek203** [comment]
I know that is:
```
    private static Sound generateSound(String sound18, String sound19) {
        Sound sound;

        if (MiscUtil.soundExists(sound18))
            sound = Sound.valueOf(sound18);   // 1.8
        else if (MiscUtil.soundExists(sound19))
            sound = Sound.valueOf(sound19);   // 1.9+
        else
            return null;                      // Else? Not supported.

        return sound;
    }
```
But it's loud and unpleasant

**Comment by utarwyn** [comment]
Yes I agree with you. To be honest I don't even remember why I have chosen the sound of an anvil when a player can't access to an enderchest. **I will change that!**

**Comment by utarwyn** [comment]
Hello @radek203, I have changed the sound played when a player cannot access its enderchest in the commit 31d18b4f26c17c044e9d9f3a8d57c6efa1fa6f41. I used the sound **VILLAGER_NO** because it fits the situation well. Is it OK for you?

**Comment by radek203** [comment]
Now is good! :)
