### ISSUE TITLE
EnderContainers inventory bug

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#7]
https://www.youtube.com/watch?v=g2vzWLN-hEc

**Comment by utarwyn** [comment]
wow, what a strange bug :confused:
I will look into this very quickly, thanks for the feedback!

**Comment by utarwyn** [comment]
I just have created a commit with a fix! You can review it here: 6d4d7d861c2ef5edf4e3230d60ff61b07c14b21a
Now this should works, is it good for you @andris155?

**Comment by andris155** [comment]
Yes, works perfectly. :)

**Comment by andris155** [comment]
Thanks!
