### ISSUE TITLE
Command issue [/ec & /ec #]

### ISSUE THREAD

**Issue by johnsoncui02** [utarwyn/EnderContainers#77]
There's a command for **/ec** where OPs are able to use. But I cannot seem to add the permission node or if there is one to allow normal users to use this command and open the GUI? Thanks

**Comment by utarwyn** [comment]
Hello! Sorry I have removed the legacy wiki page which explains all commands and permissions.. I will work on that as soon as possible. For now your can find the permission for the /ec command here: https://github.com/utarwyn/EnderContainers/wiki/Manage-permissions

**Comment by utarwyn** [comment]
New Wiki page with the command list here: https://github.com/utarwyn/EnderContainers/wiki/Command-List
If you have any idea on how to improve it, let me know! I close this issue because question as been answered.

**Sorry for the long delay! I was not very motivated.**
