### ISSUE TITLE
(Unsure) Offline UUID support

### ISSUE THREAD

**Issue by johnsoncui02** [utarwyn/EnderContainers#78]
Hi I was wondering if there's support for offline UUID specifically for cracked servers? Thanks.

**Comment by utarwyn** [comment]
Hello! Thank you for using my plugin. It should supports offline UUIDs, so do you have a bug or an error when using it on a cracked server?

**Comment by johnsoncui02** [comment]
not atm no, I am just trying to make sure to prevent potential issues.
