### ISSUE TITLE
ingame commands not working properly 

### ISSUE THREAD

**Issue by Sylensky** [utarwyn/EnderContainers#79]
**Versions**

EnderContainers version: 2.2.0
Platform version: Paper Build 201

**Describe the bug**

It appears that the ingame commands like /ecp open <player> and /ecp backup create seem to throw errors. Even if i restarted the server properly instead of dynamically loading the plugin it keeps throwing errors.

**To Reproduce**

1. load the plugin in
2. try to make a backup with /ecp backup create 1 or try to reload the plugin
3. Chat output displays it will create a backup in the background
4. internal error occured message gets displayed and the attached errors occure.

**Expected behavior**

A backup should be created with mysql if iam not wrong and it doesn't only work for flat filesystem. 

**Screenshots**

![image](https://user-images.githubusercontent.com/57076968/87188743-a5a13800-c2ef-11ea-8761-5d81faea486a.png)

**Additional context**
Here are the occuring errors for each command. 
[backup command issue.txt](https://github.com/utarwyn/EnderContainers/files/4904877/backup.command.issue.txt)
[reload command issue.txt](https://github.com/utarwyn/EnderContainers/files/4904879/reload.command.issue.txt)

**Comment by Sylensky** [comment]
Edit:
i noticed from upgrading from a previous dev build of endercontainers to the release 2.2.0 that the config.yml file needs to be removed to make atleast the /ecp reload command to work. Alltough not much changes through it since the changes won't apply properly but the reload message appears.  A plugin reload fixes it.

**Comment by utarwyn** [comment]
Thank you for the precise feedback. But I think you are using an old development build as these errors occurs in files that does not match with the ones in the final stable Jar. Try to download the latest build and tell me if all going well.

About your second issue, I will investigate more, I may have missed something when loading the configuration file. You can find the migration guide from version **2.1.0 to 2.2.0** here: https://github.com/utarwyn/EnderContainers/wiki/From-2.1.0-to-2.2.0

**Comment by utarwyn** [comment]
Is your problem been solved with the latest release?

**Comment by Sylensky** [comment]
I used the latest release 2.2.0 but it didn't worked so far and i haven't tried dev builds yet. I will update this as soon as i got more time to test. Sorry for the long reply delay.

**Comment by utarwyn** [comment]
oh... Keep me informed, and if there are still problems with the latest version, send me logs and I'll investigate :+1:

**Comment by Sylensky** [comment]
I am not sure what i did but i just restarted everything and now the ingame commands work properly even tho i restarted the server to load the plugin in before. It was already the release version so wierd thing.
