### ISSUE TITLE
Enderchest close sound not work Enderchest 1

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#8]

**Comment by utarwyn** [comment]
The reason that there is no closing sound on the first enderchest is that my plugin can use the default one. If you put the key **useVanillaEnderchest** to ***false*** in the configuration file, you will see that the bug no longer occurs. (more info [here]( https://github.com/utarwyn/EnderContainers/blob/master/src/main/resources/config.yml))

So, I can't handle the event properly but I will try to do something.

**Comment by andris155** [comment]
okay, thanks!

**Comment by utarwyn** [comment]
Now this should work for all enderchests (even the default one) thanks to this commit: 65609eedd019e98d919106530d5d1338e3265151
Hope that it brings the behavior that you want.

**Comment by andris155** [comment]
Thanks!
