### ISSUE TITLE
Plugin has to be reloaded once a users gains/removes rows from their Rank (Permissions) Compared to dynamically updating.

### ISSUE THREAD

**Issue by TriRealm** [utarwyn/EnderContainers#88]
EnderContainers version: 2.2.0 #17 (From Jenkins Download)
Platform version: Paper 1.14.4

**ALREADY POSTED ONTO SPIGOT JUST POSTING HERE SO ITS ON THE RIGHT PLATFORM**

Everytime a users rank changes that changes the rows in the chests I have to reload the plugin for it to update, it doesn't dynamically update from the users new permission for the addition or removal of rows

As stated I know I already informed you and you said it was a bug that you would look into I just thought you may like me to post it here to do it properly.

**Comment by utarwyn** [comment]
This bug should be fixed in the latest development build: https://ci.utarwyn.fr/job/EnderContainers
Sorry for the inconvenience and the wait!
