### ISSUE TITLE
1.13 update?

### ISSUE THREAD

**Issue by andris155** [utarwyn/EnderContainers#9]
Please update this plugin 1.13.

**Comment by utarwyn** [comment]
Yes I have planned to work on it next days 😄

**Comment by utarwyn** [comment]
I have just created a new branch to prepare the plugin to 1.13 servers, you can check the advancement by following this link: https://github.com/utarwyn/EnderContainers/tree/prepare-1.13

**Comment by utarwyn** [comment]
After few tests, I have just seen that EnderContainers 2.1.0 works at 90% on 1.13 servers, **so you can use it without major problems**. Otherwise, I will try to fully adapt the plugin to use the new features of the 1.13 Bukkit API.

**Comment by andris155** [comment]
Thanks!
