### ISSUE TITLE
Rename ender chests

### ISSUE THREAD

**Issue by MrMcyeet** [utarwyn/EnderContainers#92]
**Is your feature request related to a problem? Please describe.**
No problems. Small request though. Could you let us rename the enderchests of players in the config.
Mabey have like the default `Enderchest {echestnum} of {player}`
And let us customize it with a few placeholders.
It should be customizeable in the config file imho.

**Comment by utarwyn** [comment]
This enhancement has been added in #211.
Names and lore will be fully configurable from the configuration file of the plugin (with variants if needed).
